version: '2'
services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - ${GATEWAY_PORT}:3000
  sql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PW}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  authservice:
    build:
      context: authService
      dockerfile: Dockerfile
    ports:
      - ${AUTHSERVICE_PORT}:4000
    depends_on:
      - sql